// AUTO-GENERATED by scripts/extract-neetcode150.mjs from NC_150.html. Do not edit by hand.
import type { ProblemTopic } from "@/types/problems";

export const neetcode150: ProblemTopic[] = [
  {
    "name": "Arrays & Hashing",
    "problems": [
      {
        "order": 1,
        "slug": "contains-duplicate",
        "name": "Contains Duplicate",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/contains-duplicate/",
        "locked": false,
        "hints": [
          "Think about what data structure gives O(1) membership checks.",
          "A set lets you check \"have I seen this before\" in one pass.",
          "If the set's final size is smaller than the array, a duplicate exists."
        ]
      },
      {
        "order": 2,
        "slug": "valid-anagram",
        "name": "Valid Anagram",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/valid-anagram/",
        "locked": false,
        "hints": [
          "Two strings are anagrams if they have identical letter counts.",
          "Count characters with a fixed-size array or hash map, one string adds, the other subtracts.",
          "If all counts return to zero, it's a match — also handles differing lengths as an early exit."
        ]
      },
      {
        "order": 3,
        "slug": "two-sum",
        "name": "Two Sum",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/two-sum/",
        "locked": false,
        "hints": [
          "Brute force is O(n^2) — you can do it in one pass.",
          "For each number, check if its complement (target - num) was already seen.",
          "Store value to index in a hash map as you go, so the lookup is O(1)."
        ]
      },
      {
        "order": 4,
        "slug": "group-anagrams",
        "name": "Group Anagrams",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/group-anagrams/",
        "locked": false,
        "hints": [
          "Anagrams share the same letters, just reordered.",
          "A sorted version of each word makes a great group key.",
          "Map that sorted-string key to a list of original words in a hash map."
        ]
      },
      {
        "order": 5,
        "slug": "top-k-frequent-elements",
        "name": "Top K Frequent Elements",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/top-k-frequent-elements/",
        "locked": false,
        "hints": [
          "First count how often each element appears.",
          "You don't need to fully sort — bucket sort by frequency runs in O(n).",
          "Create buckets indexed by frequency (0 to n), then read off the top k from the end."
        ]
      },
      {
        "order": 6,
        "slug": "product-of-array-except-self",
        "name": "Product of Array Except Self",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/product-of-array-except-self/",
        "locked": false,
        "hints": [
          "You can't use division if a zero is present, so think prefix and suffix products.",
          "Build a prefix-product array from the left, then fold in a suffix product from the right.",
          "You can do the suffix pass in-place on the output array, using one running variable instead of a second array."
        ]
      },
      {
        "order": 7,
        "slug": "valid-sudoku",
        "name": "Valid Sudoku",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/valid-sudoku/",
        "locked": false,
        "hints": [
          "You just need to validate rules, not solve the puzzle.",
          "Track seen digits per row, per column, and per 3x3 box separately.",
          "A box's index can be computed from (row/3, col/3) to bucket cells correctly."
        ]
      },
      {
        "order": 8,
        "slug": "encode-and-decode-strings",
        "name": "Encode and Decode Strings",
        "difficulty": "M",
        "url": "https://neetcode.io/problems/string-encode-and-decode",
        "locked": true,
        "hints": [
          "You can't just join with a delimiter — the delimiter itself might appear in a string.",
          "Prefix each string with its length so decoding always knows exactly where it ends.",
          "Use a fixed separator right after the length (e.g. 5#hello) so parsing is unambiguous."
        ]
      },
      {
        "order": 9,
        "slug": "longest-consecutive-sequence",
        "name": "Longest Consecutive Sequence",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-consecutive-sequence/",
        "locked": false,
        "hints": [
          "Sorting works but the O(n) approach avoids it entirely — think hash set.",
          "Put every number in a set, then only start counting a sequence from numbers whose (num-1) isn't in the set.",
          "That check guarantees each full sequence is only ever counted once, from its start."
        ]
      }
    ]
  },
  {
    "name": "Two Pointers",
    "problems": [
      {
        "order": 10,
        "slug": "valid-palindrome",
        "name": "Valid Palindrome",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/valid-palindrome/",
        "locked": false,
        "hints": [
          "Skip non-alphanumeric characters as you compare.",
          "Use two pointers starting from both ends, moving inward.",
          "Lowercase both characters before comparing to ignore case."
        ]
      },
      {
        "order": 11,
        "slug": "two-sum-ii-input-array-is-sorted",
        "name": "Two Sum II - Input Array Is Sorted",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
        "locked": false,
        "hints": [
          "Sorted input means you don't need a hash map this time.",
          "Start pointers at both ends; the sum tells you which one to move.",
          "If the sum's too big, move the right pointer left; too small, move the left pointer right."
        ]
      },
      {
        "order": 12,
        "slug": "3sum",
        "name": "3Sum",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/3sum/",
        "locked": false,
        "hints": [
          "Fix one number, then the rest becomes a Two Sum on a sorted array.",
          "Sort first, then for each index use two pointers on the remainder to find pairs summing to its negative.",
          "Skip over duplicate values at every pointer to avoid duplicate triplets."
        ]
      },
      {
        "order": 13,
        "slug": "container-with-most-water",
        "name": "Container With Most Water",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/container-with-most-water/",
        "locked": false,
        "hints": [
          "The brute-force pair check is O(n^2) — two pointers gets you to O(n).",
          "Start at both ends; area is limited by the shorter line, so move that pointer inward.",
          "Moving the taller line inward can only ever decrease or keep the width-limited area, never help."
        ]
      },
      {
        "order": 14,
        "slug": "trapping-rain-water",
        "name": "Trapping Rain Water",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/trapping-rain-water/",
        "locked": false,
        "hints": [
          "Water trapped at any bar is limited by the shorter of the tallest walls to its left and right.",
          "Track running max-from-left and max-from-right as two pointers close in.",
          "At each step, process the side with the smaller current max first — that side's water level is now decided."
        ]
      }
    ]
  },
  {
    "name": "Sliding Window",
    "problems": [
      {
        "order": 15,
        "slug": "best-time-to-buy-and-sell-stock",
        "name": "Best Time to Buy and Sell Stock",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        "locked": false,
        "hints": [
          "You only need one pass, tracking the minimum price seen so far.",
          "At each day, the best possible profit is today's price minus the minimum-so-far.",
          "Track a running max-profit as you go rather than storing every price."
        ]
      },
      {
        "order": 16,
        "slug": "longest-substring-without-repeating-characters",
        "name": "Longest Substring Without Repeating Characters",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        "locked": false,
        "hints": [
          "Expand a window to the right; when a repeat shows up, shrink from the left.",
          "A hash set (or map of char to last index) tells you instantly if the new character is already in the window.",
          "With a map of last-seen index, you can jump the left pointer directly past the repeat instead of shrinking step by step."
        ]
      },
      {
        "order": 17,
        "slug": "longest-repeating-character-replacement",
        "name": "Longest Repeating Character Replacement",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-repeating-character-replacement/",
        "locked": false,
        "hints": [
          "You're allowed k replacements — think window where (length - count of most frequent char) is at most k.",
          "Track character counts in the current window and the count of its most frequent character.",
          "The window never needs to shrink below its best-so-far size — only slide, don't shrink unnecessarily."
        ]
      },
      {
        "order": 18,
        "slug": "permutation-in-string",
        "name": "Permutation in String",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/permutation-in-string/",
        "locked": false,
        "hints": [
          "A permutation match means the window's character counts exactly equal the target's.",
          "Use a fixed-size window (length of s1) and compare frequency counts as it slides.",
          "Track a single \"matches\" counter instead of comparing full frequency arrays every slide, for O(n)."
        ]
      },
      {
        "order": 19,
        "slug": "minimum-window-substring",
        "name": "Minimum Window Substring",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/minimum-window-substring/",
        "locked": false,
        "hints": [
          "Expand the window until it contains all required characters, then shrink from the left as much as possible.",
          "Track how many required unique characters currently have their full count satisfied.",
          "Only shrink while that satisfied count still equals the number of unique required characters."
        ]
      },
      {
        "order": 20,
        "slug": "sliding-window-maximum",
        "name": "Sliding Window Maximum",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/sliding-window-maximum/",
        "locked": false,
        "hints": [
          "A brute-force max per window is O(n*k) — a monotonic deque gets you O(n).",
          "Keep indices in a deque where corresponding values are in decreasing order.",
          "Pop smaller values off the back before pushing, and pop the front once it slides out of the window."
        ]
      }
    ]
  },
  {
    "name": "Stack",
    "problems": [
      {
        "order": 21,
        "slug": "valid-parentheses",
        "name": "Valid Parentheses",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/valid-parentheses/",
        "locked": false,
        "hints": [
          "Every closing bracket must match the most recently opened one.",
          "Push opening brackets onto a stack; on a closing bracket, check the top matches.",
          "An empty stack at the end (and never popping from empty) means it's valid."
        ]
      },
      {
        "order": 22,
        "slug": "min-stack",
        "name": "Min Stack",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/min-stack/",
        "locked": false,
        "hints": [
          "You need getMin() in O(1), so don't recompute it by scanning.",
          "Keep a second stack that tracks the running minimum alongside the main one.",
          "Push the current min again whenever a new value is less than or equal to the current min, so popping stays in sync."
        ]
      },
      {
        "order": 23,
        "slug": "evaluate-reverse-polish-notation",
        "name": "Evaluate Reverse Polish Notation",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
        "locked": false,
        "hints": [
          "Postfix notation means operators come after their operands — a stack processes this naturally.",
          "Push numbers; on an operator, pop two, apply it, and push the result back.",
          "Watch operand order for subtraction and division — the second-popped value comes first."
        ]
      },
      {
        "order": 24,
        "slug": "generate-parentheses",
        "name": "Generate Parentheses",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/generate-parentheses/",
        "locked": false,
        "hints": [
          "This is backtracking, not a formula — build strings and prune invalid branches.",
          "Track counts of open and close brackets used so far.",
          "You can add a close bracket only if close count is less than open count, and an open bracket only if open count is less than n."
        ]
      },
      {
        "order": 25,
        "slug": "daily-temperatures",
        "name": "Daily Temperatures",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/daily-temperatures/",
        "locked": false,
        "hints": [
          "For each day you need the next day with a higher temperature — a stack tracks \"waiting\" days.",
          "Keep a monotonically decreasing stack of indices (temperatures decreasing top to bottom).",
          "When a warmer day appears, pop and resolve every colder day still on the stack in one pass."
        ]
      },
      {
        "order": 26,
        "slug": "car-fleet",
        "name": "Car Fleet",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/car-fleet/",
        "locked": false,
        "hints": [
          "Sort by starting position — only the car closest to the destination can \"lead\" a fleet.",
          "Compute each car's arrival time if it never had to slow down.",
          "Process from closest-to-destination backward; a car merges into the fleet ahead if its time is at most the fleet leader's."
        ]
      },
      {
        "order": 27,
        "slug": "largest-rectangle-in-histogram",
        "name": "Largest Rectangle in Histogram",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        "locked": false,
        "hints": [
          "For each bar, you want the widest rectangle where it's the shortest bar.",
          "A monotonic increasing stack of (index, height) tracks candidates efficiently.",
          "When a shorter bar appears, pop taller bars and compute their max rectangle using the current index as the right boundary."
        ]
      }
    ]
  },
  {
    "name": "Binary Search",
    "problems": [
      {
        "order": 28,
        "slug": "binary-search",
        "name": "Binary Search",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/binary-search/",
        "locked": false,
        "hints": [
          "Compare the middle element to the target and eliminate half the space each time.",
          "Use left <= right as your loop condition to avoid missing the last element.",
          "Watch for integer overflow when computing mid — use left + (right-left)/2."
        ]
      },
      {
        "order": 29,
        "slug": "search-a-2d-matrix",
        "name": "Search a 2D Matrix",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/search-a-2d-matrix/",
        "locked": false,
        "hints": [
          "Rows are sorted and each row's first element is greater than the previous row's last — think of it as one flattened sorted array.",
          "Convert a single mid index into (row, col) using division and modulo by the row width.",
          "Binary search that flattened index space directly instead of searching rows then columns separately."
        ]
      },
      {
        "order": 30,
        "slug": "koko-eating-bananas",
        "name": "Koko Eating Bananas",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/koko-eating-bananas/",
        "locked": false,
        "hints": [
          "You're not searching the array — you're searching over possible \"eating speeds.\"",
          "For a given speed, you can compute the total hours needed in one pass.",
          "Binary search the speed: if hours needed is at most h, try slower; otherwise go faster."
        ]
      },
      {
        "order": 31,
        "slug": "find-minimum-in-rotated-sorted-array",
        "name": "Find Minimum in Rotated Sorted Array",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
        "locked": false,
        "hints": [
          "The array is sorted then rotated — one half is always properly ordered.",
          "Compare the middle to the rightmost element to decide which half contains the rotation point.",
          "If mid's value is greater than right's value, the minimum is to the right of mid; otherwise it's at or before mid."
        ]
      },
      {
        "order": 32,
        "slug": "search-in-rotated-sorted-array",
        "name": "Search in Rotated Sorted Array",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        "locked": false,
        "hints": [
          "At every step, at least one half of the current range is normally sorted.",
          "Figure out which half is sorted first, then check if the target falls in that half's range.",
          "If the target's in the sorted half's range, search there; otherwise search the other half."
        ]
      },
      {
        "order": 33,
        "slug": "time-based-key-value-store",
        "name": "Time Based Key-Value Store",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/time-based-key-value-store/",
        "locked": false,
        "hints": [
          "Each key maps to a list of (timestamp, value) pairs, added in increasing timestamp order.",
          "That means each key's list is already sorted by timestamp — binary search applies.",
          "Find the largest timestamp in that key's list that is at most the query timestamp."
        ]
      },
      {
        "order": 34,
        "slug": "median-of-two-sorted-arrays",
        "name": "Median of Two Sorted Arrays",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        "locked": false,
        "hints": [
          "Merging both arrays is O(m+n) — the log-time approach binary searches a partition point.",
          "Binary search a partition in the smaller array; the partition in the other array is then determined.",
          "A valid partition has every left-side element at most every right-side element across both arrays."
        ]
      }
    ]
  },
  {
    "name": "Linked List",
    "problems": [
      {
        "order": 35,
        "slug": "reverse-linked-list",
        "name": "Reverse Linked List",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/reverse-linked-list/",
        "locked": false,
        "hints": [
          "You need to flip every next pointer — track the previous node as you go.",
          "At each node, save its next before overwriting it, then point back to the previous node.",
          "Also solvable recursively: reverse the rest of the list first, then fix the current node's links."
        ]
      },
      {
        "order": 36,
        "slug": "merge-two-sorted-lists",
        "name": "Merge Two Sorted Lists",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/merge-two-sorted-lists/",
        "locked": false,
        "hints": [
          "This is like the merge step of merge sort, but on linked lists.",
          "Use a dummy head node so you don't need special-case logic for the first node.",
          "At each step, attach the smaller of the two current nodes and advance only that list."
        ]
      },
      {
        "order": 37,
        "slug": "reorder-list",
        "name": "Reorder List",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/reorder-list/",
        "locked": false,
        "hints": [
          "The target order interleaves the first half with the reversed second half.",
          "Find the middle with slow/fast pointers, reverse the second half, then merge the two halves alternately.",
          "Be careful to cleanly split the list in two and null-terminate the first half before reversing the second."
        ]
      },
      {
        "order": 38,
        "slug": "remove-nth-node-from-end-of-list",
        "name": "Remove Nth Node From End of List",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        "locked": false,
        "hints": [
          "You want to avoid two full passes (one to count, one to remove).",
          "Move one pointer n steps ahead first, then move both pointers together until the lead reaches the end.",
          "Use a dummy node before the head so removing the actual head node needs no special case."
        ]
      },
      {
        "order": 39,
        "slug": "copy-list-with-random-pointer",
        "name": "Copy List with Random Pointer",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/copy-list-with-random-pointer/",
        "locked": false,
        "hints": [
          "The tricky part is the random pointer, which can point anywhere, including forward.",
          "A hash map from original node to cloned node lets you look up any random target instantly.",
          "Do it in two passes: first create all clone nodes, then wire up next and random using the map."
        ]
      },
      {
        "order": 40,
        "slug": "add-two-numbers",
        "name": "Add Two Numbers",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/add-two-numbers/",
        "locked": false,
        "hints": [
          "Digits are stored in reverse order, so you can add from the least significant digit directly.",
          "Track a carry value as you sum corresponding digits from both lists.",
          "Don't forget a final extra node if a carry remains after both lists are exhausted."
        ]
      },
      {
        "order": 41,
        "slug": "linked-list-cycle",
        "name": "Linked List Cycle",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/linked-list-cycle/",
        "locked": false,
        "hints": [
          "You need O(1) space, so a visited-set isn't the intended solution.",
          "Use two pointers moving at different speeds — one step and two steps at a time.",
          "If there's a cycle, the faster pointer will eventually lap and equal the slower one."
        ]
      },
      {
        "order": 42,
        "slug": "find-the-duplicate-number",
        "name": "Find the Duplicate Number",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/find-the-duplicate-number/",
        "locked": false,
        "hints": [
          "You can't modify the array or use extra space, which rules out sorting or a set.",
          "Treat each value as a \"next pointer\" (index to arr[index]) — a duplicate creates a cycle.",
          "Floyd's cycle detection (same idea as Linked List Cycle) finds the duplicate as the cycle's entry point."
        ]
      },
      {
        "order": 43,
        "slug": "lru-cache",
        "name": "LRU Cache",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/lru-cache/",
        "locked": false,
        "hints": [
          "You need O(1) get and put, so no scanning to find the least-recently-used item.",
          "Combine a hash map (key to node) with a doubly linked list ordered by recency.",
          "On every get or put, move that node to the front; evict from the back when over capacity."
        ]
      },
      {
        "order": 44,
        "slug": "merge-k-sorted-lists",
        "name": "Merge k Sorted Lists",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/merge-k-sorted-lists/",
        "locked": false,
        "hints": [
          "Merging two at a time repeatedly works, but a heap gets you a cleaner O(n log k).",
          "Push the head of every list into a min-heap keyed by value.",
          "Pop the smallest, append it to the result, then push its next node (if any) back into the heap."
        ]
      },
      {
        "order": 45,
        "slug": "reverse-nodes-in-k-group",
        "name": "Reverse Nodes in k-Group",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
        "locked": false,
        "hints": [
          "You're reversing the list in fixed-size chunks — check if a full group of k even exists first.",
          "Reverse each group of k like a standard linked-list reversal, tracking the group's original head and tail.",
          "Connect the previous group's tail to the new group's head, and leave any remaining shorter group unreversed."
        ]
      }
    ]
  },
  {
    "name": "Trees",
    "problems": [
      {
        "order": 46,
        "slug": "invert-binary-tree",
        "name": "Invert Binary Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/invert-binary-tree/",
        "locked": false,
        "hints": [
          "\"Invert\" means swap every node's left and right children.",
          "A simple recursive swap at every node, then recurse into both (now-swapped) children, solves it.",
          "This also works iteratively with a queue or stack instead of recursion."
        ]
      },
      {
        "order": 47,
        "slug": "maximum-depth-of-binary-tree",
        "name": "Maximum Depth of Binary Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        "locked": false,
        "hints": [
          "The depth of a tree is 1 plus the deeper of its two subtrees.",
          "Recurse on left and right, take the max, and add 1 for the current node.",
          "A null node has depth 0 — that's your base case."
        ]
      },
      {
        "order": 48,
        "slug": "diameter-of-binary-tree",
        "name": "Diameter of Binary Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/diameter-of-binary-tree/",
        "locked": false,
        "hints": [
          "The diameter is a path length, and it doesn't have to pass through the root.",
          "At every node, the longest path through it is left-depth plus right-depth.",
          "Track a running max of that sum while a helper function returns depth upward, so you only traverse once."
        ]
      },
      {
        "order": 49,
        "slug": "balanced-binary-tree",
        "name": "Balanced Binary Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/balanced-binary-tree/",
        "locked": false,
        "hints": [
          "Balanced means every node's two subtrees differ in height by at most 1.",
          "A naive check recomputes height repeatedly — instead, have height-checking return -1 as an \"unbalanced\" signal.",
          "Once any subtree reports unbalanced, short-circuit and propagate that -1 straight up without further checking."
        ]
      },
      {
        "order": 50,
        "slug": "same-tree",
        "name": "Same Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/same-tree/",
        "locked": false,
        "hints": [
          "Two trees are the same only if every corresponding node matches, including null positions.",
          "If both nodes are null, that's a match; if only one is null, that's a mismatch.",
          "Otherwise compare values, then recursively check the left and right subtrees."
        ]
      },
      {
        "order": 51,
        "slug": "subtree-of-another-tree",
        "name": "Subtree of Another Tree",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/subtree-of-another-tree/",
        "locked": false,
        "hints": [
          "You can reuse a \"same tree\" check as a helper here.",
          "Walk every node in the main tree, and at each one check if that same-tree comparison matches the subtree.",
          "Try the match starting at every node, not just the root — the subtree could start anywhere."
        ]
      },
      {
        "order": 52,
        "slug": "lowest-common-ancestor-of-a-binary-search-tree",
        "name": "Lowest Common Ancestor of a Binary Search Tree",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
        "locked": false,
        "hints": [
          "A BST's ordering tells you which direction to go without checking both subtrees.",
          "If both target values are less than the current node, go left; if both are greater, go right.",
          "The moment the two values split (one at or below current, one at or above), that current node is the answer."
        ]
      },
      {
        "order": 53,
        "slug": "binary-tree-level-order-traversal",
        "name": "Binary Tree Level Order Traversal",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        "locked": false,
        "hints": [
          "You need to group nodes by level, so a plain DFS needs extra bookkeeping — BFS is more natural.",
          "Use a queue, and process it one full level at a time by tracking the queue's size at the start of each level.",
          "For each of those \"size\" nodes, dequeue it, record its value, and enqueue its children before moving to the next level."
        ]
      },
      {
        "order": 54,
        "slug": "binary-tree-right-side-view",
        "name": "Binary Tree Right Side View",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/binary-tree-right-side-view/",
        "locked": false,
        "hints": [
          "You want the last node visible at each level, looking from the right.",
          "A level-order (BFS) traversal naturally lets you grab the last node processed at each level.",
          "Alternatively, DFS right-before-left and record the first node seen at each new depth."
        ]
      },
      {
        "order": 55,
        "slug": "count-good-nodes-in-binary-tree",
        "name": "Count Good Nodes in Binary Tree",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
        "locked": false,
        "hints": [
          "A node is \"good\" if no ancestor on its path from the root has a greater value.",
          "Pass the maximum value seen so far down the recursion as you descend.",
          "At each node, compare it to that running max — if it's at least as big, count it and update the max for its children."
        ]
      },
      {
        "order": 56,
        "slug": "validate-binary-search-tree",
        "name": "Validate Binary Search Tree",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/validate-binary-search-tree/",
        "locked": false,
        "hints": [
          "Checking only \"left child less than node less than right child\" locally isn't enough — bounds must hold for the whole subtree.",
          "Pass a valid (min, max) range down through the recursion.",
          "Each node must fall within its inherited range, then tighten that range for its left and right children."
        ]
      },
      {
        "order": 57,
        "slug": "kth-smallest-element-in-a-bst",
        "name": "Kth Smallest Element in a BST",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
        "locked": false,
        "hints": [
          "An in-order traversal of a BST visits nodes in sorted order.",
          "Do an in-order traversal and just count nodes as you go.",
          "You can stop as soon as you hit the kth node — no need to traverse the whole tree."
        ]
      },
      {
        "order": 58,
        "slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
        "name": "Construct Binary Tree from Preorder and Inorder Traversal",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
        "locked": false,
        "hints": [
          "Preorder's first element is always the current subtree's root.",
          "Find that root's position in the inorder slice — everything left of it is the left subtree, everything right is the right subtree.",
          "A hash map from value to inorder index turns that lookup into O(1) instead of a scan."
        ]
      },
      {
        "order": 59,
        "slug": "binary-tree-maximum-path-sum",
        "name": "Binary Tree Maximum Path Sum",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        "locked": false,
        "hints": [
          "A path can start and end anywhere, and doesn't have to pass through the root.",
          "At each node, the best path through it is node value plus the best of (left, 0) plus the best of (right, 0), clamping negative contributions to zero.",
          "What you return upward to the parent is different — only node value plus the better single side, since a path can't branch through a node it's passing through."
        ]
      },
      {
        "order": 60,
        "slug": "serialize-and-deserialize-binary-tree",
        "name": "Serialize and Deserialize Binary Tree",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        "locked": false,
        "hints": [
          "You need a format that unambiguously marks null children so deserialization isn't guesswork.",
          "A preorder traversal that explicitly writes a marker (like N) for every null child works well.",
          "Deserialize by consuming that same preorder stream recursively, exactly mirroring how you wrote it."
        ]
      }
    ]
  },
  {
    "name": "Tries",
    "problems": [
      {
        "order": 61,
        "slug": "implement-trie-prefix-tree",
        "name": "Implement Trie (Prefix Tree)",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/implement-trie-prefix-tree/",
        "locked": false,
        "hints": [
          "Each node needs children (one per possible character) and a flag marking \"a word ends here.\"",
          "Insert by walking/creating a child node per character, then marking the last node as end-of-word.",
          "search() and startsWith() are nearly identical — the only difference is checking that end-of-word flag at the end."
        ]
      },
      {
        "order": 62,
        "slug": "design-add-and-search-words-data-structure",
        "name": "Design Add and Search Words Data Structure",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        "locked": false,
        "hints": [
          "This is a trie, plus a wildcard character that can match any letter.",
          "On a normal character, descend into exactly one child; on the wildcard, you must try every child.",
          "That wildcard case means search needs to be recursive (or use a stack) to explore multiple branches."
        ]
      },
      {
        "order": 63,
        "slug": "word-search-ii",
        "name": "Word Search II",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/word-search-ii/",
        "locked": false,
        "hints": [
          "Searching for each word separately over the board is far too slow with many words.",
          "Put all words into a trie, then do one DFS over the board following trie paths instead of one search per word.",
          "Prune trie branches once a word is found so future searches skip already-completed paths."
        ]
      }
    ]
  },
  {
    "name": "Heap / Priority Queue",
    "problems": [
      {
        "order": 64,
        "slug": "kth-largest-element-in-a-stream",
        "name": "Kth Largest Element in a Stream",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
        "locked": false,
        "hints": [
          "You need the kth largest after every addition, not just once.",
          "A min-heap of size k always has the kth largest sitting at its top.",
          "On each add, push the new value, and if the heap exceeds size k, pop the smallest."
        ]
      },
      {
        "order": 65,
        "slug": "last-stone-weight",
        "name": "Last Stone Weight",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/last-stone-weight/",
        "locked": false,
        "hints": [
          "You always need the two current heaviest stones — a max-heap gives you that instantly.",
          "Pop the top two, and if they differ, push the difference back in.",
          "A min-heap can simulate a max-heap by pushing negated values."
        ]
      },
      {
        "order": 66,
        "slug": "k-closest-points-to-origin",
        "name": "K Closest Points to Origin",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/k-closest-points-to-origin/",
        "locked": false,
        "hints": [
          "You don't need to fully sort all points, just find the closest k.",
          "A max-heap of size k (by distance) lets you discard the farthest point whenever the heap overflows.",
          "Compare squared distances to avoid unnecessary square-root calls."
        ]
      },
      {
        "order": 67,
        "slug": "kth-largest-element-in-an-array",
        "name": "Kth Largest Element in an Array",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        "locked": false,
        "hints": [
          "Full sorting is O(n log n) — quickselect averages O(n).",
          "Quickselect partitions like quicksort, but only recurses into the one side that contains the target index.",
          "A min-heap of size k is a simpler, if slightly slower, O(n log k) alternative."
        ]
      },
      {
        "order": 68,
        "slug": "task-scheduler",
        "name": "Task Scheduler",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/task-scheduler/",
        "locked": false,
        "hints": [
          "The most frequent task drives the minimum possible schedule length.",
          "Picture \"slots\" of size (cooldown + 1), filled first by the most frequent tasks.",
          "The answer is the max of (total tasks) and the slot-based calculation using the most frequent task's count."
        ]
      },
      {
        "order": 69,
        "slug": "design-twitter",
        "name": "Design Twitter",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/design-twitter/",
        "locked": false,
        "hints": [
          "You need the 10 most recent tweets across everyone a user follows, merged and ordered by time.",
          "Track a global increasing timestamp/counter alongside each tweet.",
          "Use a heap to merge each followed user's most recent tweets efficiently rather than sorting everything."
        ]
      },
      {
        "order": 70,
        "slug": "find-median-from-data-stream",
        "name": "Find Median from Data Stream",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/find-median-from-data-stream/",
        "locked": false,
        "hints": [
          "Sorting on every insert is too slow — you want the middle without a full sort.",
          "Keep two heaps: a max-heap for the smaller half of numbers, a min-heap for the larger half.",
          "Keep the heaps balanced in size (differing by at most 1); the median comes from the top(s) of the heaps."
        ]
      }
    ]
  },
  {
    "name": "Backtracking",
    "problems": [
      {
        "order": 71,
        "slug": "subsets",
        "name": "Subsets",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/subsets/",
        "locked": false,
        "hints": [
          "Every element has two choices at each step: include it, or don't.",
          "A recursive function that branches on include vs skip for each index generates all subsets.",
          "There's no need to check for duplicates here — all elements are distinct, so no extra pruning is required."
        ]
      },
      {
        "order": 72,
        "slug": "combination-sum",
        "name": "Combination Sum",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/combination-sum/",
        "locked": false,
        "hints": [
          "The same number can be reused, so your recursion should allow revisiting the current index.",
          "At each step, either include the current candidate again or move to the next candidate.",
          "Sort first so you can break early once the remaining target goes negative."
        ]
      },
      {
        "order": 73,
        "slug": "permutations",
        "name": "Permutations",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/permutations/",
        "locked": false,
        "hints": [
          "Order matters here, unlike Subsets — every arrangement counts as distinct.",
          "Track which elements are already used in the current path, and try every unused one at each position.",
          "Swapping elements in place is a memory-efficient alternative to a separate used-tracking array."
        ]
      },
      {
        "order": 74,
        "slug": "subsets-ii",
        "name": "Subsets II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/subsets-ii/",
        "locked": false,
        "hints": [
          "Duplicate values in the input mean naive subset generation will produce duplicate subsets.",
          "Sort the array first so duplicates sit next to each other.",
          "At each recursion level, skip a candidate if it equals the previous one and the previous one wasn't included at this same level."
        ]
      },
      {
        "order": 75,
        "slug": "combination-sum-ii",
        "name": "Combination Sum II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/combination-sum-ii/",
        "locked": false,
        "hints": [
          "Unlike Combination Sum, each number can only be used once here.",
          "Sort first, then advance the index by one each recursive call instead of allowing reuse.",
          "Use the same skip-identical-siblings trick as Subsets II to avoid duplicate combinations."
        ]
      },
      {
        "order": 76,
        "slug": "word-search",
        "name": "Word Search",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/word-search/",
        "locked": false,
        "hints": [
          "This is a grid DFS where you also need to avoid revisiting a cell within the current path.",
          "Mark a cell as visited before recursing into its neighbors, then unmark it on the way back (backtrack).",
          "Exit early the moment a full match is found rather than exploring further unnecessarily."
        ]
      },
      {
        "order": 77,
        "slug": "palindrome-partitioning",
        "name": "Palindrome Partitioning",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/palindrome-partitioning/",
        "locked": false,
        "hints": [
          "You want every way to cut the string such that each piece is a palindrome.",
          "At each position, try every possible next cut, but only recurse into cuts that form a palindrome.",
          "Precomputing which substrings are palindromes avoids re-checking the same substring repeatedly."
        ]
      },
      {
        "order": 78,
        "slug": "letter-combinations-of-a-phone-number",
        "name": "Letter Combinations of a Phone Number",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
        "locked": false,
        "hints": [
          "Each digit maps to a fixed set of letters — this is a Cartesian product built one digit at a time.",
          "Recurse digit by digit, appending one of that digit's letters to the current path each time.",
          "An empty input should return an empty list, not a list containing an empty string — handle that edge case."
        ]
      },
      {
        "order": 79,
        "slug": "n-queens",
        "name": "N-Queens",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/n-queens/",
        "locked": false,
        "hints": [
          "Place one queen per row, and only need to check that column, diagonal, and anti-diagonal are free.",
          "Track used columns and both diagonal directions with sets for O(1) conflict checks.",
          "A cell's two diagonals can be identified by (row - col) and (row + col), which stay constant along each diagonal."
        ]
      }
    ]
  },
  {
    "name": "Graphs",
    "problems": [
      {
        "order": 80,
        "slug": "number-of-islands",
        "name": "Number of Islands",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/number-of-islands/",
        "locked": false,
        "hints": [
          "Each unvisited land cell you find is the start of a new island.",
          "DFS or BFS from that cell, marking every connected land cell as visited, \"sinks\" the whole island at once.",
          "Count how many times you start a fresh DFS/BFS from an unvisited land cell — that count is your answer."
        ]
      },
      {
        "order": 81,
        "slug": "clone-graph",
        "name": "Clone Graph",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/clone-graph/",
        "locked": false,
        "hints": [
          "You need to recreate every node and every edge without infinite-looping on cycles.",
          "A hash map from original node to cloned node lets you detect \"already cloned\" and avoid revisiting.",
          "Clone a node the first time you see it, then recurse into its neighbors, wiring up clones via the map."
        ]
      },
      {
        "order": 82,
        "slug": "max-area-of-island",
        "name": "Max Area of Island",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/max-area-of-island/",
        "locked": false,
        "hints": [
          "Very similar to Number of Islands, but now you need each island's size, not just the count.",
          "Have your DFS/BFS return the count of cells visited during that flood-fill.",
          "Track a running max across every island's returned size."
        ]
      },
      {
        "order": 83,
        "slug": "pacific-atlantic-water-flow",
        "name": "Pacific Atlantic Water Flow",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
        "locked": false,
        "hints": [
          "Checking every cell's path to both oceans directly is expensive — try working backward from the oceans instead.",
          "DFS inland from every Pacific-bordering cell, and separately from every Atlantic-bordering cell, moving only to equal-or-higher neighbors.",
          "A cell that got reached from both searches can flow to both oceans — that's your answer set."
        ]
      },
      {
        "order": 84,
        "slug": "surrounded-regions",
        "name": "Surrounded Regions",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/surrounded-regions/",
        "locked": false,
        "hints": [
          "An O region is only safe if it touches the border somewhere.",
          "Start DFS/BFS from every border O first, and mark everything reachable from those as safe.",
          "Afterward, flip every remaining unmarked O to X — those never had a path to the border."
        ]
      },
      {
        "order": 85,
        "slug": "rotting-oranges",
        "name": "Rotting Oranges",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/rotting-oranges/",
        "locked": false,
        "hints": [
          "All oranges rot simultaneously each minute, which points to a multi-source BFS, not one BFS per rotten orange.",
          "Push every initially-rotten orange into the queue at once, then process level by level, one minute per level.",
          "If any fresh orange remains unreached after the BFS finishes, the answer is -1."
        ]
      },
      {
        "order": 86,
        "slug": "walls-and-gates",
        "name": "Walls and Gates",
        "difficulty": "M",
        "url": "https://neetcode.io/problems/islands-and-treasure",
        "locked": true,
        "hints": [
          "Similar shape to Rotting Oranges — every gate can act as a BFS source simultaneously.",
          "Push all gates into a queue together, then BFS outward, filling in distances as you reach each empty room.",
          "A room only needs updating the first time it's reached, since BFS guarantees that's the shortest distance."
        ]
      },
      {
        "order": 87,
        "slug": "course-schedule",
        "name": "Course Schedule",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/course-schedule/",
        "locked": false,
        "hints": [
          "This is really \"does this dependency graph contain a cycle?\"",
          "Track each course's in-degree (prerequisite count) and process courses with zero remaining prerequisites first.",
          "If you can process every course this way (Kahn's algorithm), there's no cycle; if some remain stuck, a cycle exists."
        ]
      },
      {
        "order": 88,
        "slug": "course-schedule-ii",
        "name": "Course Schedule II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/course-schedule-ii/",
        "locked": false,
        "hints": [
          "Same cycle-detection idea as Course Schedule, but now you also need the valid order itself.",
          "Kahn's algorithm naturally produces a valid order as a side effect of processing zero-in-degree nodes.",
          "If the resulting order doesn't include every course, a cycle exists — return an empty array."
        ]
      },
      {
        "order": 89,
        "slug": "redundant-connection",
        "name": "Redundant Connection",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/redundant-connection/",
        "locked": false,
        "hints": [
          "You're looking for the one edge that turns a tree into a graph with a cycle.",
          "Union-Find lets you add edges one at a time and detect the instant one connects two already-connected nodes.",
          "That first edge connecting an already-unified pair is your answer — no need to look further."
        ]
      },
      {
        "order": 90,
        "slug": "number-of-connected-components-in-an-undirected-graph",
        "name": "Number of Connected Components in an Undirected Graph",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
        "locked": false,
        "hints": [
          "Each group of mutually reachable nodes counts as one component.",
          "Union-Find (or repeated DFS from unvisited nodes) groups nodes into components efficiently.",
          "With Union-Find, the number of distinct roots left after processing every edge is your answer."
        ]
      },
      {
        "order": 91,
        "slug": "graph-valid-tree",
        "name": "Graph Valid Tree",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/graph-valid-tree/",
        "locked": false,
        "hints": [
          "A valid tree needs exactly n-1 edges and full connectivity — check both.",
          "If the edge count isn't exactly n-1, you can return false immediately without further checks.",
          "Otherwise, Union-Find (or a single DFS/BFS) confirms whether all nodes end up in one connected group."
        ]
      },
      {
        "order": 92,
        "slug": "word-ladder",
        "name": "Word Ladder",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/word-ladder/",
        "locked": false,
        "hints": [
          "Treat every valid word as a graph node, connected to other words one letter apart — then it's shortest path.",
          "BFS naturally finds the shortest transformation sequence, since it explores level by level.",
          "Generate neighbors by trying every letter substitution at every position, checking each candidate against the word set."
        ]
      }
    ]
  },
  {
    "name": "Advanced Graphs",
    "problems": [
      {
        "order": 93,
        "slug": "reconstruct-itinerary",
        "name": "Reconstruct Itinerary",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/reconstruct-itinerary/",
        "locked": false,
        "hints": [
          "You need to use every ticket exactly once, in an order that's lexicographically smallest when multiple valid itineraries exist.",
          "This is really an Eulerian path — visit neighbors in sorted order, but only finalize a stop after exhausting its options.",
          "Build the route by appending nodes in a post-order DFS fashion, then reverse the result at the end."
        ]
      },
      {
        "order": 94,
        "slug": "min-cost-to-connect-all-points",
        "name": "Min Cost to Connect All Points",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
        "locked": false,
        "hints": [
          "You want the cheapest set of edges connecting all points — that's a Minimum Spanning Tree.",
          "Prim's algorithm grows the tree one cheapest available edge at a time from a min-heap.",
          "Track visited points so you don't re-add edges to points already included in the tree."
        ]
      },
      {
        "order": 95,
        "slug": "network-delay-time",
        "name": "Network Delay Time",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/network-delay-time/",
        "locked": false,
        "hints": [
          "You want the shortest time for a signal to reach every node — single-source shortest path.",
          "Dijkstra's algorithm, using a min-heap keyed by current best travel time, fits directly.",
          "The answer is the max travel time across all nodes — if any node's unreached, return -1."
        ]
      },
      {
        "order": 96,
        "slug": "swim-in-rising-water",
        "name": "Swim in Rising Water",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/swim-in-rising-water/",
        "locked": false,
        "hints": [
          "You want the path where the single highest elevation crossed is as small as possible.",
          "A modified Dijkstra works: instead of summing distances, track the max elevation seen so far on each path.",
          "A min-heap ordered by that running max, always expanding the currently-lowest-max cell, gets you there efficiently."
        ]
      },
      {
        "order": 97,
        "slug": "alien-dictionary",
        "name": "Alien Dictionary",
        "difficulty": "H",
        "url": "https://neetcode.io/problems/foreign-dictionary",
        "locked": true,
        "hints": [
          "Word order implies letter order — the first differing character between adjacent words gives you one ordering constraint.",
          "Build a directed graph of \"this letter comes before that letter,\" then topologically sort it.",
          "Watch the edge case where a later word is a prefix of an earlier one — that's invalid and has no valid ordering."
        ]
      },
      {
        "order": 98,
        "slug": "cheapest-flights-within-k-stops",
        "name": "Cheapest Flights Within K Stops",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        "locked": false,
        "hints": [
          "Plain Dijkstra doesn't account for the \"at most K stops\" limit directly.",
          "Bellman-Ford, relaxing edges for at most K+1 rounds, naturally respects the stop limit.",
          "Use the previous round's costs (not values already updated this round) so you don't chain more than one extra stop per round."
        ]
      }
    ]
  },
  {
    "name": "1-D Dynamic Programming",
    "problems": [
      {
        "order": 99,
        "slug": "climbing-stairs",
        "name": "Climbing Stairs",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/climbing-stairs/",
        "locked": false,
        "hints": [
          "To reach step n, you came from either step n-1 or step n-2.",
          "That means ways(n) = ways(n-1) + ways(n-2) — this is just Fibonacci in disguise.",
          "You only need the last two values at any point, so you can solve it in O(1) space."
        ]
      },
      {
        "order": 100,
        "slug": "min-cost-climbing-stairs",
        "name": "Min Cost Climbing Stairs",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/min-cost-climbing-stairs/",
        "locked": false,
        "hints": [
          "Similar recurrence to Climbing Stairs, but now each step choice has an associated cost.",
          "cost-to-reach(i) = cost[i] + the smaller of cost-to-reach(i-1) and cost-to-reach(i-2).",
          "You can start from either step 0 or step 1 for free — the answer is the min cost to get past the last step."
        ]
      },
      {
        "order": 101,
        "slug": "house-robber",
        "name": "House Robber",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/house-robber/",
        "locked": false,
        "hints": [
          "You can't rob two adjacent houses — decide, at each house, to include it or skip it.",
          "best(i) = max(best(i-1), best(i-2) + value[i]) — either skip this house or take it plus the best two houses back.",
          "Only the previous two computed values are ever needed, so this reduces to O(1) space."
        ]
      },
      {
        "order": 102,
        "slug": "house-robber-ii",
        "name": "House Robber II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/house-robber-ii/",
        "locked": false,
        "hints": [
          "The houses are in a circle now, so the first and last house can't both be robbed.",
          "Run the regular House Robber logic twice: once excluding the last house, once excluding the first.",
          "The answer is the max of those two runs — this sidesteps the circular constraint entirely."
        ]
      },
      {
        "order": 103,
        "slug": "longest-palindromic-substring",
        "name": "Longest Palindromic Substring",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-palindromic-substring/",
        "locked": false,
        "hints": [
          "Every palindrome has a center — either a single character or between two characters.",
          "Try expanding outward from every possible center, growing while both sides still match.",
          "There are 2n-1 centers total — check them all and track the longest expansion."
        ]
      },
      {
        "order": 104,
        "slug": "palindromic-substrings",
        "name": "Palindromic Substrings",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/palindromic-substrings/",
        "locked": false,
        "hints": [
          "Same expand-around-center idea as Longest Palindromic Substring, but now you count every valid expansion instead of tracking just the longest.",
          "Every successful expansion step (even a length-1 or length-2 one) counts as one palindrome.",
          "Total count equals the sum, over all centers, of how far each one successfully expands."
        ]
      },
      {
        "order": 105,
        "slug": "decode-ways",
        "name": "Decode Ways",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/decode-ways/",
        "locked": false,
        "hints": [
          "Each position can potentially be decoded alone, or paired with the next digit — but not always.",
          "ways(i) = ways(i-1) if digit i is valid alone, plus ways(i-2) if digits i-1 and i form a valid 10-26 pair.",
          "A zero can never stand alone — it's only valid as the second digit of a 10 or 20 pair."
        ]
      },
      {
        "order": 106,
        "slug": "coin-change",
        "name": "Coin Change",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/coin-change/",
        "locked": false,
        "hints": [
          "This is bottom-up: figure out the min coins for every amount from 0 up to the target.",
          "minCoins(amount) = 1 + the minimum over every coin at most amount of minCoins(amount - coin).",
          "Initialize impossible amounts to infinity, and if the target amount is still infinity at the end, return -1."
        ]
      },
      {
        "order": 107,
        "slug": "maximum-product-subarray",
        "name": "Maximum Product Subarray",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/maximum-product-subarray/",
        "locked": false,
        "hints": [
          "A single negative number can flip a very small product into the largest one — track both running max and running min.",
          "At each element, the new max is the largest of (element alone, element times old max, element times old min).",
          "Update both max and min together each step, since a min can become a max instantly if the next number's negative."
        ]
      },
      {
        "order": 108,
        "slug": "word-break",
        "name": "Word Break",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/word-break/",
        "locked": false,
        "hints": [
          "You want to know, for every prefix of the string, whether it can be fully segmented into dictionary words.",
          "canBreak(i) is true if some earlier index j has canBreak(j) true and the substring from j to i is in the dictionary.",
          "A hash set for O(1) dictionary lookups keeps this efficient across many substring checks."
        ]
      },
      {
        "order": 109,
        "slug": "longest-increasing-subsequence",
        "name": "Longest Increasing Subsequence",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-increasing-subsequence/",
        "locked": false,
        "hints": [
          "The O(n^2) version compares every pair — there's an O(n log n) version using binary search.",
          "Maintain a list representing the smallest possible tail for an increasing subsequence of each length.",
          "For each new number, binary search that list for where it belongs and replace there (or append if it's the largest so far)."
        ]
      },
      {
        "order": 110,
        "slug": "partition-equal-subset-sum",
        "name": "Partition Equal Subset Sum",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/partition-equal-subset-sum/",
        "locked": false,
        "hints": [
          "If the total sum is odd, it's immediately impossible to split evenly.",
          "This reduces to \"can some subset sum to exactly half the total\" — classic 0/1 knapsack.",
          "Track which sums are reachable using a boolean array, updating it in reverse to avoid reusing an item twice."
        ]
      }
    ]
  },
  {
    "name": "2-D Dynamic Programming",
    "problems": [
      {
        "order": 111,
        "slug": "unique-paths",
        "name": "Unique Paths",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/unique-paths/",
        "locked": false,
        "hints": [
          "The number of ways to reach a cell is the sum of ways to reach the cell above it and the cell to its left.",
          "The entire first row and first column only have exactly one possible path each.",
          "This can be computed with a single 1D array reused across rows, instead of a full 2D grid."
        ]
      },
      {
        "order": 112,
        "slug": "longest-common-subsequence",
        "name": "Longest Common Subsequence",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/longest-common-subsequence/",
        "locked": false,
        "hints": [
          "Compare characters of both strings position by position, building a 2D table of best-so-far lengths.",
          "If the current characters match, extend the diagonal value by 1; otherwise take the max of the cell above or to the left.",
          "Use an extra row and column of zeros as padding so you don't need special-case logic at the string boundaries."
        ]
      },
      {
        "order": 113,
        "slug": "best-time-to-buy-and-sell-stock-with-cooldown",
        "name": "Best Time to Buy and Sell Stock with Cooldown",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
        "locked": false,
        "hints": [
          "After selling, you can't buy the very next day — that's the twist versus a plain buy/sell problem.",
          "Track separate running states for holding a stock, just sold (in cooldown), and free to buy.",
          "Each day, each state's new value depends only on yesterday's states — no need to store more than the previous day."
        ]
      },
      {
        "order": 114,
        "slug": "coin-change-ii",
        "name": "Coin Change II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/coin-change-ii/",
        "locked": false,
        "hints": [
          "Unlike Coin Change (min coins), here you're counting the number of distinct combinations that sum to the target.",
          "Process one coin type at a time, updating reachable-amount counts, so order doesn't create duplicate combinations.",
          "Iterate amounts upward (not downward) per coin, since reusing the same coin multiple times is allowed here."
        ]
      },
      {
        "order": 115,
        "slug": "target-sum",
        "name": "Target Sum",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/target-sum/",
        "locked": false,
        "hints": [
          "Assigning plus or minus to each number is really choosing a subset to negate.",
          "If S is the total sum and P is the positive-subset sum, the negative subset sums to S-P, and you need P - (S-P) to equal target.",
          "That reframes it as: count subsets summing to (target + S) / 2 — a counting variant of the subset-sum knapsack."
        ]
      },
      {
        "order": 116,
        "slug": "interleaving-string",
        "name": "Interleaving String",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/interleaving-string/",
        "locked": false,
        "hints": [
          "Track how much of each of the two source strings you've consumed to build a prefix of the result.",
          "dp[i][j] is true if the first i characters of s1 and first j characters of s2 can interleave into the first i+j characters of s3.",
          "At each cell, check whether the next needed character can come validly from s1's next character, from s2's next character, or neither."
        ]
      },
      {
        "order": 117,
        "slug": "longest-increasing-path-in-a-matrix",
        "name": "Longest Increasing Path in a Matrix",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        "locked": false,
        "hints": [
          "From every cell, the longest increasing path is 1 plus the best result from any strictly-greater neighbor.",
          "Plain DFS recomputes the same cells repeatedly — cache each cell's answer once computed (memoization).",
          "Because values only increase along a path, there are no cycles to worry about, so memoized DFS is safe."
        ]
      },
      {
        "order": 118,
        "slug": "distinct-subsequences",
        "name": "Distinct Subsequences",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/distinct-subsequences/",
        "locked": false,
        "hints": [
          "You're counting ways to pick characters from s (keeping order) to spell out t exactly.",
          "dp[i][j] is the number of ways using the first i characters of s to form the first j characters of t.",
          "If s[i] matches t[j], you can either use it or skip it — add both possibilities; if it doesn't match, you can only skip it in s."
        ]
      },
      {
        "order": 119,
        "slug": "edit-distance",
        "name": "Edit Distance",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/edit-distance/",
        "locked": false,
        "hints": [
          "At each pair of positions, you're choosing the cheapest of insert, delete, or replace.",
          "If the current characters match, no edit's needed — carry forward the diagonal value unchanged.",
          "Otherwise take 1 plus the minimum of the three neighboring cells (insert, delete, replace)."
        ]
      },
      {
        "order": 120,
        "slug": "burst-balloons",
        "name": "Burst Balloons",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/burst-balloons/",
        "locked": false,
        "hints": [
          "Think about which balloon you burst LAST in a given range, not first — that reframes it into clean subproblems.",
          "dp[i][j] is the best score for bursting all balloons strictly between i and j, given i and j survive as boundaries.",
          "Try every possible last-balloon-burst k inside (i, j), and combine dp[i][k] + dp[k][j] + the product of the three boundary values."
        ]
      },
      {
        "order": 121,
        "slug": "regular-expression-matching",
        "name": "Regular Expression Matching",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/regular-expression-matching/",
        "locked": false,
        "hints": [
          "A star means zero-or-more of the preceding character, which forces you to consider two branches at once.",
          "dp[i][j] represents whether the first i characters of s match the first j characters of the pattern.",
          "On a star, you must handle both \"match zero of the preceding char\" and \"match one more and stay on this pattern position.\""
        ]
      }
    ]
  },
  {
    "name": "Greedy",
    "problems": [
      {
        "order": 122,
        "slug": "maximum-subarray",
        "name": "Maximum Subarray",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/maximum-subarray/",
        "locked": false,
        "hints": [
          "If your running sum ever goes negative, it can never help a future subarray — you're better off restarting from zero.",
          "Keep a running sum, resetting it to 0 whenever it dips below zero, and track the max sum seen.",
          "This is Kadane's algorithm — a single pass, O(n) time, O(1) space."
        ]
      },
      {
        "order": 123,
        "slug": "jump-game",
        "name": "Jump Game",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/jump-game/",
        "locked": false,
        "hints": [
          "You don't need to know every path — just whether the farthest reachable index ever covers the end.",
          "Track the farthest index reachable so far as you scan left to right.",
          "If you ever reach an index beyond your current farthest-reachable point, you're stuck — return false immediately."
        ]
      },
      {
        "order": 124,
        "slug": "jump-game-ii",
        "name": "Jump Game II",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/jump-game-ii/",
        "locked": false,
        "hints": [
          "You want the minimum number of jumps, not just whether reaching the end is possible.",
          "Track the current jump's reachable boundary and the farthest boundary reachable with one more jump.",
          "Increment the jump count exactly when you reach the current boundary, then advance both boundaries."
        ]
      },
      {
        "order": 125,
        "slug": "gas-station",
        "name": "Gas Station",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/gas-station/",
        "locked": false,
        "hints": [
          "If the total gas is less than the total cost, no valid starting station exists at all.",
          "Track a running tank total; whenever it goes negative, no station before this point could have been a valid start either.",
          "The station right after the last point the tank went negative is the unique valid starting point (when a solution exists)."
        ]
      },
      {
        "order": 126,
        "slug": "hand-of-straights",
        "name": "Hand of Straights",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/hand-of-straights/",
        "locked": false,
        "hints": [
          "You need to form consecutive-value groups of a fixed size from the whole hand.",
          "Count occurrences of each card, then always try to build a group starting from the smallest remaining card.",
          "If any of the groupSize consecutive cards needed is unavailable, the hand can't be rearranged — return false."
        ]
      },
      {
        "order": 127,
        "slug": "merge-triplets-to-form-target-triplet",
        "name": "Merge Triplets to Form Target Triplet",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/",
        "locked": false,
        "hints": [
          "A triplet is only useful if none of its values exceed the corresponding target value.",
          "Filter out any triplet where any coordinate overshoots the target's corresponding coordinate.",
          "Among the remaining valid triplets, check if each target coordinate is matched by at least one of them."
        ]
      },
      {
        "order": 128,
        "slug": "partition-labels",
        "name": "Partition Labels",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/partition-labels/",
        "locked": false,
        "hints": [
          "A letter's partition must extend at least to that letter's last occurrence anywhere in the string.",
          "Precompute the last index of every character first.",
          "Extend the current partition's boundary to the max last-occurrence of every character seen so far in it; close the partition when you reach that boundary."
        ]
      },
      {
        "order": 129,
        "slug": "valid-parenthesis-string",
        "name": "Valid Parenthesis String",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/valid-parenthesis-string/",
        "locked": false,
        "hints": [
          "A star can act as an open bracket, a close bracket, or nothing, so tracking one exact count of open brackets isn't enough.",
          "Track a range (minimum possible open count, maximum possible open count) as you scan.",
          "If the max ever drops below zero, it's invalid; at the end, the string is valid if the minimum can be brought down to zero."
        ]
      }
    ]
  },
  {
    "name": "Intervals",
    "problems": [
      {
        "order": 130,
        "slug": "insert-interval",
        "name": "Insert Interval",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/insert-interval/",
        "locked": false,
        "hints": [
          "The existing intervals are already sorted and non-overlapping, which you can take advantage of.",
          "Add every interval that ends before the new one starts, untouched.",
          "Merge all intervals that overlap the new one into a single combined interval, then add every interval that starts after it ends."
        ]
      },
      {
        "order": 131,
        "slug": "merge-intervals",
        "name": "Merge Intervals",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/merge-intervals/",
        "locked": false,
        "hints": [
          "Sort by start time first — overlaps can only happen between intervals that are now adjacent.",
          "Walk through sorted intervals, merging into the last added result whenever the current one's start is at or before that result's end.",
          "When merging, update the result's end to the max of the two ends being merged, not just the new interval's end."
        ]
      },
      {
        "order": 132,
        "slug": "non-overlapping-intervals",
        "name": "Non-overlapping Intervals",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/non-overlapping-intervals/",
        "locked": false,
        "hints": [
          "Think in reverse: instead of counting removals, maximize how many intervals you can keep.",
          "Sort by end time, and greedily keep an interval whenever it starts at or after the last kept interval's end.",
          "Sorting by end time (not start time) is the key detail — it's what makes the greedy choice provably optimal."
        ]
      },
      {
        "order": 133,
        "slug": "meeting-rooms",
        "name": "Meeting Rooms",
        "difficulty": "E",
        "url": "https://neetcode.io/problems/meeting-schedule",
        "locked": true,
        "hints": [
          "This just asks whether ANY two meetings overlap.",
          "Sort by start time, then check each meeting's start against the previous meeting's end.",
          "Any start time earlier than the previous meeting's end time means overlap exists."
        ]
      },
      {
        "order": 134,
        "slug": "meeting-rooms-ii",
        "name": "Meeting Rooms II",
        "difficulty": "M",
        "url": "https://neetcode.io/problems/meeting-schedule-ii",
        "locked": true,
        "hints": [
          "You need the max number of meetings happening simultaneously at any point, not just whether any overlap.",
          "Separately sort all start times and all end times, then walk through them together.",
          "Each start increments a room counter, each end (when it comes before or with the next start) decrements it — track the running max."
        ]
      },
      {
        "order": 135,
        "slug": "minimum-interval-to-include-each-query",
        "name": "Minimum Interval to Include Each Query",
        "difficulty": "H",
        "url": "https://leetcode.com/problems/minimum-interval-to-include-each-query/",
        "locked": false,
        "hints": [
          "For each query, you want the smallest interval that contains it — process both in a smart order to avoid rechecking everything.",
          "Sort both intervals and queries by value, and use a min-heap of active intervals keyed by interval size.",
          "As you sweep through queries in increasing order, add newly-started intervals to the heap and pop expired ones off the top before reading the answer."
        ]
      }
    ]
  },
  {
    "name": "Math & Geometry",
    "problems": [
      {
        "order": 136,
        "slug": "rotate-image",
        "name": "Rotate Image",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/rotate-image/",
        "locked": false,
        "hints": [
          "You must rotate the matrix in place, without allocating a second matrix.",
          "Transpose the matrix first (swap across the diagonal), then reverse each row.",
          "Transpose plus reverse-rows together produce exactly a 90-degree clockwise rotation."
        ]
      },
      {
        "order": 137,
        "slug": "spiral-matrix",
        "name": "Spiral Matrix",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/spiral-matrix/",
        "locked": false,
        "hints": [
          "Track four shrinking boundaries — top, bottom, left, right — and walk each edge in turn.",
          "Traverse right along the top boundary, down the right boundary, left along the bottom, up along the left, then shrink all four boundaries inward.",
          "After each direction, re-check that top is at or above bottom and left is at or before right before continuing, since a non-square matrix can finish mid-cycle."
        ]
      },
      {
        "order": 138,
        "slug": "set-matrix-zeroes",
        "name": "Set Matrix Zeroes",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/set-matrix-zeroes/",
        "locked": false,
        "hints": [
          "You need O(1) extra space, so a separate copy of the matrix isn't the intended solution.",
          "Use the matrix's own first row and first column as markers for which rows/columns need zeroing.",
          "Handle the first row and first column's own zero-status with one or two separate boolean flags, since they double as your marker space."
        ]
      },
      {
        "order": 139,
        "slug": "happy-number",
        "name": "Happy Number",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/happy-number/",
        "locked": false,
        "hints": [
          "Repeatedly summing squared digits either reaches 1, or falls into a repeating cycle that never reaches 1.",
          "This is a cycle-detection problem — Floyd's slow/fast pointer trick applies directly to the sequence of values.",
          "Alternatively, a hash set of seen values lets you detect a repeat (and therefore an infinite non-1 cycle) directly."
        ]
      },
      {
        "order": 140,
        "slug": "plus-one",
        "name": "Plus One",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/plus-one/",
        "locked": false,
        "hints": [
          "Adding one only cascades into a carry when a digit is 9.",
          "Starting from the last digit, if it's less than 9, just increment it and you're done immediately.",
          "If every digit was a 9 (all become 0), you need one extra leading 1 digit at the front."
        ]
      },
      {
        "order": 141,
        "slug": "powx-n",
        "name": "Pow(x, n)",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/powx-n/",
        "locked": false,
        "hints": [
          "Multiplying x by itself n times is O(n) — you can do better by repeatedly squaring.",
          "x^n equals (x^(n/2))^2 when n is even, and x times (x^(n/2))^2 when n is odd (using integer division).",
          "A negative n just means computing the positive-power result and then taking its reciprocal."
        ]
      },
      {
        "order": 142,
        "slug": "multiply-strings",
        "name": "Multiply Strings",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/multiply-strings/",
        "locked": false,
        "hints": [
          "You can't convert to native integers if the numbers can be arbitrarily large.",
          "Multiply digit by digit like grade-school long multiplication, placing each partial product at the right offset in a result array.",
          "Digit i of the first number times digit j of the second number always lands at result positions i+j and i+j+1 — accumulate there and handle carries at the end."
        ]
      },
      {
        "order": 143,
        "slug": "detect-squares",
        "name": "Detect Squares",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/detect-squares/",
        "locked": false,
        "hints": [
          "For every added point, you need fast lookups of \"how many points exist at a given coordinate.\"",
          "A hash map counting occurrences of each (x, y) point gives O(1) existence/count checks.",
          "For a query point, try every existing point sharing its x-coordinate as one diagonal corner, then check if the other two required corners exist too."
        ]
      }
    ]
  },
  {
    "name": "Bit Manipulation",
    "problems": [
      {
        "order": 144,
        "slug": "single-number",
        "name": "Single Number",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/single-number/",
        "locked": false,
        "hints": [
          "Every number except one appears exactly twice — think about an operation where duplicates cancel out.",
          "XOR-ing a number with itself gives 0, and XOR-ing with 0 leaves a number unchanged.",
          "XOR every element together — every pair of duplicates cancels, leaving only the single number."
        ]
      },
      {
        "order": 145,
        "slug": "number-of-1-bits",
        "name": "Number of 1 Bits",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/number-of-1-bits/",
        "locked": false,
        "hints": [
          "You want to count set bits, which you can do by repeatedly isolating the lowest set bit.",
          "n AND (n-1) clears the lowest set bit of n — count how many times you can do that before n becomes 0.",
          "This runs in time proportional to the number of set bits, not the total bit width."
        ]
      },
      {
        "order": 146,
        "slug": "counting-bits",
        "name": "Counting Bits",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/counting-bits/",
        "locked": false,
        "hints": [
          "You can reuse previously computed answers instead of recounting bits from scratch for every number.",
          "The bit count of i equals the bit count of (i with its lowest set bit removed), plus 1.",
          "i AND (i-1) is that \"lowest set bit removed\" value, and it's always smaller than i, so it's already computed."
        ]
      },
      {
        "order": 147,
        "slug": "reverse-bits",
        "name": "Reverse Bits",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/reverse-bits/",
        "locked": false,
        "hints": [
          "You're reversing the order of all 32 bits, not the value itself.",
          "Build the result bit by bit: shift the result left, then OR in the current lowest bit of the input.",
          "Shift the input right by 1 each iteration so its next lowest bit is ready to read, across all 32 iterations."
        ]
      },
      {
        "order": 148,
        "slug": "missing-number",
        "name": "Missing Number",
        "difficulty": "E",
        "url": "https://leetcode.com/problems/missing-number/",
        "locked": false,
        "hints": [
          "You know the full expected set (0 to n) — compare it against what's actually present.",
          "The sum of 0 through n minus the sum of the given array leaves exactly the missing number.",
          "XOR-ing every index 0 through n with every array value also isolates the missing number, avoiding any overflow concerns with large sums."
        ]
      },
      {
        "order": 149,
        "slug": "sum-of-two-integers",
        "name": "Sum of Two Integers",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/sum-of-two-integers/",
        "locked": false,
        "hints": [
          "You can't use plus or minus directly, so build addition from bitwise operations instead.",
          "XOR gives you the sum of two bits ignoring carry; AND, shifted left by 1, gives you the carry.",
          "Repeat that XOR/AND-shift process, feeding the carry back in, until there's no carry left to add."
        ]
      },
      {
        "order": 150,
        "slug": "reverse-integer",
        "name": "Reverse Integer",
        "difficulty": "M",
        "url": "https://leetcode.com/problems/reverse-integer/",
        "locked": false,
        "hints": [
          "You need to catch 32-bit signed integer overflow, which reversing digits can easily cause.",
          "Pull off the last digit with modulo 10, build the reversed number with result = result*10 + digit, and strip that digit off the original by dividing by 10.",
          "Check for overflow before each multiply-by-10 step, comparing against the 32-bit int boundaries rather than after the fact."
        ]
      }
    ]
  }
];
